# Generated by Django 4.1 on 2022-08-27 20:43

from django.db import migrations
import os
def generate_ninja_names(apps, schema_editor):

    NinjaName = apps.get_model("ninja_generator", "NinjaName")
    db_alias = schema_editor.connection.alias

    # From: https://www.geeksforgeeks.org/read-a-file-line-by-line-in-python/
    # Using readlines() 
    ninjaFile = open('ninja_generator/migrations/data/ninja_names.txt')
    
    Lines = ninjaFile.readlines()
    
    # Strips the newline character
    for line in Lines:
        NinjaName.objects.using(db_alias).create(
            name= line.strip()
        )

    ninjaFile.close()

class Migration(migrations.Migration):

    dependencies = [
        ("ninja_generator", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(generate_ninja_names),
    ]
