# Generated by Django 4.1 on 2022-08-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ninja_generator", "0002_auto_20220827_1643"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
