version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    build: .  
    command: sh -c "/wait && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: app:django
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - APP_DB_ENGINE=django.db.backends.postgresql
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=100
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=10
    container_name: django_container    
    depends_on:
      - db
      - migration
  migration:
    image: app:django
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - APP_DB_ENGINE=django.db.backends.postgresql
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=100
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=10
    command: sh -c "/wait && python manage.py migrate"
    volumes:
      - .:/django
    depends_on:
      - db
